export type Field = {
  key: string;
  label: string;
  type?: string;
  options?: string[];
  relation?: string;
  optional?: boolean;
  readOnly?: boolean;
};
export type PortalResource = {
  title: string;
  group: string;
  permission: string;
  fields: Field[];
  readOnly?: boolean;
  immutable?: boolean;
};
export function permissionLabel(permission: string) {
  const [area, action] = permission.split(":");
  const areas: Record<string, string> = {
    catalog: "Katalog",
    stock: "Stok",
    orders: "Sipariş",
    purchasing: "Satın alma",
    cost: "Maliyet",
    settings: "Ayarlar ve üyeler",
    audit: "Denetim kaydı",
    production: "Üretim",
    hr: "Personel",
    billing: "Abonelik",
    profile: "Hesabım",
    reports: "Raporlar",
  };
  const actions: Record<string, string> = {
    read: "görüntüle",
    write: "ekle ve düzenle",
    approve: "onayla",
  };
  return `${areas[area] || area}: ${actions[action] || action}`;
}
const f = (
  key: string,
  label: string,
  type = "text",
  optional = false,
): Field => ({ key, label, type, optional });
const relation = (
  key: string,
  label: string,
  target: string,
  optional = false,
): Field => ({ key, label, relation: target, optional });
const choices = (key: string, label: string, options: string[]): Field => ({
  key,
  label,
  options,
});
export const portalResources: Record<string, PortalResource> = {
  materials: {
    title: "Malzemeler",
    group: "Katalog",
    permission: "catalog",
    fields: [
      f("code", "Kod"),
      f("name", "Ad"),
      f("unit", "Birim"),
      f("minimum", "Kritik seviye", "decimal"),
    ],
  },
  products: {
    title: "Ürünler ve varyantlar",
    group: "Katalog",
    permission: "catalog",
    fields: [f("code", "Kod"), f("name", "Ad"), f("unit", "Birim")],
  },
  recipes: {
    title: "Çok seviyeli reçeteler",
    group: "Katalog",
    permission: "catalog",
    fields: [
      relation("product_id", "Ürün", "products"),
      relation("material_id", "Malzeme", "materials", true),
      relation("component_product_id", "Alt ürün", "products", true),
      f("quantity", "Miktar", "decimal"),
    ],
  },
  units: {
    title: "Birimler",
    group: "Katalog",
    permission: "catalog",
    fields: [
      f("code", "Kod"),
      f("name", "Ad"),
      relation("base_unit_id", "Temel birim", "units", true),
      f("factor", "Dönüşüm katsayısı", "decimal"),
    ],
  },
  partners: {
    title: "Müşteri ve tedarikçiler",
    group: "İş ortakları",
    permission: "catalog",
    fields: [
      f("name", "Ad"),
      choices("kind", "İlişki", ["customer", "supplier", "both"]),
    ],
  },
  "partner-codes": {
    title: "İş ortağı kodları",
    group: "İş ortakları",
    permission: "catalog",
    fields: [
      relation("partner_id", "İş ortağı", "partners"),
      relation("material_id", "Malzeme", "materials"),
      f("code", "İş ortağı kodu"),
    ],
  },
  warehouses: {
    title: "Depolar ve sahiplik",
    group: "Stok",
    permission: "stock",
    fields: [
      f("name", "Depo adı"),
      relation(
        "owner_partner_id",
        "Sahibi (boş: kendi firmanız)",
        "partners",
        true,
      ),
    ],
  },
  balances: {
    title: "Depo bakiyeleri",
    group: "Stok",
    permission: "stock",
    readOnly: true,
    fields: [],
  },
  transfers: {
    title: "Depolar arası aktarım",
    group: "Stok",
    permission: "stock",
    readOnly: true,
    fields: [
      relation("material_id", "Malzeme", "materials"),
      relation("source_warehouse_id", "Kaynak depo", "warehouses"),
      relation("destination_warehouse_id", "Hedef depo", "warehouses"),
      f("quantity", "Miktar", "decimal"),
      f("note", "Açıklama", "text", true),
    ],
  },
  "stock-counts": {
    title: "Stok sayımları",
    group: "Stok",
    permission: "stock",
    readOnly: true,
    fields: [],
  },
  movements: {
    title: "Stok hareketleri",
    group: "Stok",
    permission: "stock",
    readOnly: true,
    fields: [],
  },
  reservations: {
    title: "Rezervasyonlar",
    group: "Stok",
    permission: "stock",
    readOnly: true,
    fields: [],
  },
  orders: {
    title: "Siparişler",
    group: "Sipariş",
    permission: "orders",
    fields: [
      f("code", "Sipariş kodu"),
      relation("partner_id", "Müşteri", "partners", true),
      f("due_date", "Teslim tarihi", "date"),
      choices("status", "Durum", ["draft", "active", "done", "cancelled"]),
    ],
  },
  "order-lines": {
    title: "Sipariş kalemleri",
    group: "Sipariş",
    permission: "orders",
    fields: [
      relation("order_id", "Sipariş", "orders"),
      relation("product_id", "Ürün", "products"),
      f("quantity", "Miktar", "decimal"),
    ],
  },
  requirements: {
    title: "Malzeme ihtiyaçları",
    group: "Sipariş",
    permission: "orders",
    fields: [
      relation("order_id", "Sipariş", "orders"),
      relation("material_id", "Malzeme", "materials"),
      f("quantity", "Miktar", "decimal"),
      choices("source", "Tedarik sorumlusu", [
        "undecided",
        "own",
        "customer",
        "customer_supplier",
      ]),
    ],
  },
  quotes: {
    title: "Tedarikçi teklifleri",
    group: "Satın alma",
    permission: "purchasing",
    fields: [
      relation("partner_id", "Tedarikçi", "partners"),
      relation("material_id", "Malzeme", "materials"),
      f("unit_price", "Birim fiyat", "decimal"),
      choices("currency", "Para birimi", ["TRY", "USD", "EUR", "GBP"]),
      f("lead_days", "Termin (gün)", "number"),
      f("minimum", "Asgari miktar", "decimal"),
      f("pack_size", "Paket miktarı", "decimal"),
      f("payment_terms", "Ödeme koşulları", "text", true),
      f("valid_until", "Geçerlilik tarihi", "date"),
    ],
  },
  purchases: {
    title: "Satın alma onayları",
    group: "Satın alma",
    permission: "purchasing",
    immutable: true,
    fields: [
      relation("material_id", "Malzeme", "materials"),
      relation("partner_id", "Tedarikçi", "partners", true),
      f("quantity", "Miktar", "decimal"),
      f("unit_price", "Birim fiyat", "decimal"),
      choices("currency", "Para birimi", ["TRY", "USD", "EUR", "GBP"]),
    ],
  },
  stations: {
    title: "Üretim istasyonları",
    group: "Üretim",
    permission: "production",
    fields: [f("name", "İstasyon adı"), f("capacity", "Kapasite", "decimal")],
  },
  "work-orders": {
    title: "İş emirleri",
    group: "Üretim",
    permission: "production",
    immutable: true,
    fields: [
      relation("order_id", "Sipariş", "orders"),
      relation("station_id", "İstasyon", "stations"),
      f("quantity", "Hedef miktar", "decimal"),
      f("assigned_to", "Atanan kullanıcı", "text", true),
    ],
  },
  quality: {
    title: "Kalite kontrolleri",
    group: "Üretim",
    permission: "production",
    immutable: true,
    fields: [
      relation("work_order_id", "İş emri", "work-orders"),
      choices("result", "Sonuç", ["pass", "fail", "hold"]),
      f("sample_size", "Örnek miktarı", "decimal"),
      f("note", "Kontrol notu", "text", true),
    ],
  },
  employees: {
    title: "Personel",
    group: "Personel",
    permission: "hr",
    fields: [
      f("name", "Ad soyad"),
      f("code", "Personel kodu"),
      f("job_title", "Görev", "text", true),
    ],
  },
  shifts: {
    title: "Vardiyalar",
    group: "Personel",
    permission: "hr",
    fields: [
      relation("employee_id", "Personel", "employees"),
      relation("station_id", "İstasyon", "stations", true),
      f("start_at", "Başlangıç", "datetime-local"),
      f("end_at", "Bitiş", "datetime-local"),
      f("note", "Not", "text", true),
    ],
  },
  attendance: {
    title: "Devam kayıtları",
    group: "Personel",
    permission: "hr",
    fields: [
      relation("employee_id", "Personel", "employees"),
      f("arrived_at", "Geliş", "datetime-local"),
      f("left_at", "Çıkış", "datetime-local", true),
    ],
  },
  cases: {
    title: "Müşteri talepleri",
    group: "İş ortakları",
    permission: "orders",
    fields: [
      relation("partner_id", "Müşteri", "partners"),
      relation("order_id", "Sipariş", "orders", true),
      f("subject", "Konu"),
      f("message", "Açıklama", "textarea"),
      choices("status", "Durum", ["open", "investigating", "resolved"]),
      f("satisfaction", "Memnuniyet (1–5)", "number", true),
    ],
  },
  "notification-rules": {
    title: "Bildirim kuralları",
    group: "Yönetim",
    permission: "settings",
    fields: [
      choices("event", "Olay", ["low_stock", "purchase_pending", "order_due"]),
      choices("channel", "Kanal", ["email", "in_app"]),
      f("recipient", "Alıcı e-posta", "email"),
      f("enabled", "Bildirim etkin", "checkbox"),
    ],
  },
  notifications: {
    title: "Bildirimler",
    group: "Hesabım",
    permission: "profile",
    readOnly: true,
    fields: [],
  },
  roles: {
    title: "Roller ve izinler",
    group: "Yönetim",
    permission: "settings",
    readOnly: true,
    fields: [],
  },
  settings: {
    title: "Firma ayarları",
    group: "Yönetim",
    permission: "settings",
    readOnly: true,
    fields: [
      choices("locale", "Firma dili", ["tr", "en", "ar", "zh", "ru"]),
      f("timezone", "Saat dilimi"),
      f("approval_limit", "Onay eşiği", "decimal"),
      f("retention_days", "Saklama süresi (gün)", "number"),
    ],
  },
  subscriptions: {
    title: "Abonelik",
    group: "Yönetim",
    permission: "billing",
    readOnly: true,
    fields: [],
  },
  audit: {
    title: "Denetim kaydı",
    group: "Yönetim",
    permission: "audit",
    readOnly: true,
    fields: [],
  },
  "privacy-requests": {
    title: "Veri hakları",
    group: "Hesabım",
    permission: "profile",
    immutable: true,
    fields: [
      choices("kind", "Talep", ["export", "erase", "correct"]),
      f("message", "Açıklama", "textarea", true),
    ],
  },
};
export const valueLabels: Record<string, string> = {
  in: "Giriş",
  out: "Çıkış",
  customer: "Müşteri",
  supplier: "Tedarikçi",
  both: "Müşteri ve tedarikçi",
  draft: "Taslak",
  active: "Aktif",
  done: "Tamamlandı",
  cancelled: "İptal",
  pending: "Onay bekliyor",
  approved: "Onaylandı",
  rejected: "Reddedildi",
  undecided: "Karar bekliyor",
  own: "Kendi firmamız",
  customer_supplier: "Müşterinin tedarikçisi",
  queued: "Sırada",
  running: "Üretimde",
  paused: "Beklemede",
  pass: "Uygun",
  fail: "Uygun değil",
  hold: "İncelenecek",
  open: "Açık",
  investigating: "İnceleniyor",
  resolved: "Çözüldü",
  low_stock: "Kritik stok",
  purchase_pending: "Satın alma onayı",
  order_due: "Teslim yaklaşması",
  in_app: "Uygulama içi",
  email: "E-posta",
  export: "Veri dışa aktarımı",
  erase: "Veri silme",
  correct: "Veri düzeltme",
  trialing: "Deneme",
  past_due: "Ödeme bekliyor",
  held: "Rezerve",
  released: "Serbest",
  consumed: "Kullanıldı",
};
export const columnLabels: Record<string, string> = {
  id: "Kayıt",
  tenant_id: "Firma",
  name: "Ad",
  code: "Kod",
  quantity: "Miktar",
  minimum: "Kritik seviye",
  unit: "Birim",
  status: "Durum",
  due_date: "Teslim",
  material_id: "Malzeme",
  product_id: "Ürün",
  partner_id: "İş ortağı",
  warehouse_id: "Depo",
  order_id: "Sipariş",
  created_at: "Oluşturulma",
  unit_price: "Birim fiyat",
  currency: "Para birimi",
  reserved: "Rezerve",
  required: "Gereken",
  available: "Kullanılabilir",
  shortage: "Eksik",
  note: "Not",
  actor_id: "İşlemi yapan",
  entity: "Kayıt türü",
  action: "İşlem",
  old_value: "Önce",
  new_value: "Sonra",
  permissions: "İzinler",
  mfa_required: "MFA zorunlu",
  role: "Rol",
  user_id: "Kullanıcı",
  active: "Aktif",
  trial_ends_at: "Deneme sonu",
  period_ends_at: "Dönem sonu",
  plan: "Paket",
  extra_seats: "Ek kullanıcı",
  version: "Sürüm",
  completed: "Tamamlanan",
  scrap: "Fire",
  station_id: "İstasyon",
  employee_id: "Personel",
  work_order_id: "İş emri",
  result: "Sonuç",
  expected_quantity: "Sayım öncesi miktar",
  counted_quantity: "Sayılan miktar",
  difference: "Sayım farkı",
  reason: "Gerekçe",
  counted_by: "Sayan kullanıcı",
  source_warehouse_id: "Kaynak depo",
  destination_warehouse_id: "Hedef depo",
  transferred_by: "Aktaran kullanıcı",
  transfer_id: "Aktarım kaydı",
};
